name: Deploy to GitHub Pages

on:
  push:
    branches: [Production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci
        working-directory: Portfolio-portal-service

      - name: Build site
        run: npm run build
        working-directory: Portfolio-portal-service

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Portfolio-portal-service/dist
          cname: www.nguyencongquy.id.vn
